{{ define ".boto" }}
  [Credentials]

  # google credentials ("gs://" URIs):
  gs_access_key_id = {{ .Values.gcs.accessKeyId }}
  gs_secret_access_key = {{ .Values.gcs.secretAccessKey }}

  [Boto]
  https_validate_certificates = True

  [GSUtil]
  default_nguage = en
  api_version = 1
  default_project_id = {{ .Values.gcs.projectId }}
{{ end }}
{{- if .Values.gcs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-gcs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  .boto: |
    {{ include ".boto" . | b64enc }}
{{- end }}
