kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-backup-reader
rules:
- apiGroups: ["*"]
  resources: [
    "configmaps",
    "cronjobs",
    "deployments",
    "daemonsets",
    "ingresses",
    "namespaces",
    "networkpolicies",
    "replicationcontrollers",
    "services",
    "statefulsets",
    "storageclasses",
    "thirdpartyresources"
  ]
  verbs: ["get", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-backup
  namespace: default
subjects:
- kind: ServiceAccount
  name: kube-backup
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-backup-reader
  apiGroup: rbac.authorization.k8s.io
